/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Fri Jul 14 2017 02:34:02 GMT+0530 (India Standard Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ENV = {};

//# sourceMappingURL=data:application/json;charset=utf8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFwcC9zaGFyZWQvY29uc3RhbnQvZW52LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7R0FTRzs7O0FBSVUsUUFBQSxHQUFHLEdBQVcsRUFDMUIsQ0FBQyIsImZpbGUiOiJhcHAvc2hhcmVkL2NvbnN0YW50L2Vudi5qcyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxuICogVEhJUyBGSUxFIElTIEdFTkVSQVRFRCBieSBgZ3VscCBlbnZgIGNvbW1hbmQgZnJvbSBgZW52Lmpzb25gXG4gKiBHZW5lcmF0ZWQgb24gRnJpIEp1bCAxNCAyMDE3IDAyOjM0OjAyIEdNVCswNTMwIChJbmRpYSBTdGFuZGFyZCBUaW1lKVxuICpcbiAqIE1ha2Ugc3VyZSB0aGUga2V5cyBpbiBgZW52Lm1vZGVsLnRzYCBleGlzdCBpbiBgZW52Lmpzb25gXG4gKiBvdGhlcndpc2UgaXQnbGwgdGhyb3cgbWVzc2FnZSBsaWtlIHRoaXNcbiAqIFByb3BlcnR5ICc8bWlzc2luZy1rZXk+JyBpcyBtaXNzaW5nIGluIHR5cGUgJ3t9J1xuICpcbiAqIEZlZWwgZnJlZSB0byBtb2RpZnkgZm9yIGRpcmVjdCB1cGRhdGVzIGluIGRldmVsb3BtZW50XG4gKi9cblxuaW1wb3J0IHsgQXBwRW52IH0gZnJvbSAnLi9lbnYubW9kZWwnO1xuXG5leHBvcnQgY29uc3QgRU5WOiBBcHBFbnYgPSB7XG59O1xuIl19
